#!/usr/bin/env node
/**
 * Guard that every live reference to uWebSockets.js names the SAME tag as the
 * `optionalDependencies` pin in package.json. The addon is a GitHub-hosted
 * native build pinned by tag, so an install line, a doc snippet or a test
 * harness naming an older tag hands someone a different binary than the one the
 * adapter is built and tested against - and because the dependency is optional,
 * npm reports nothing when the wrong one is fetched. That skew has shipped
 * twice: once from a spec hardcoded in the build entry point, and once from the
 * README install blocks plus the test harness sitting seven tags behind a bump.
 *
 * The rule, and where its boundary is:
 *
 *   - MATCHED: the install-spec form `uWebSockets.js#<ref>` - the copy-pasteable
 *     thing (an `npm install uNetworking/uWebSockets.js#<tag>` line, a
 *     dependency value, a JSDoc example of one). Whoever reads it acts on it,
 *     so it has to be current.
 *   - NOT MATCHED: a bare version named in prose ("pinned to v20.67.0 (was
 *     v20.60.0)"). CHANGELOG.md and MIGRATION.md say exactly that, on purpose,
 *     about the past. A guard that forces history to be rewritten on every bump
 *     is worse than the drift it prevents, so the pattern cannot see prose at
 *     all: it only fires on a spec someone could paste into a shell.
 *   - SKIPPED WHOLE: CHANGELOG.md, append-only history whose entries may quote
 *     the full spec of their day and must keep quoting it verbatim. (The shipped
 *     log is untracked and only tracked files are scanned, so it never arrives
 *     here in the first place.)
 *   - REPORTED, NOT ENFORCED: lockfiles. They are generated, and a stale one is
 *     corrected by rerunning `npm install` in that directory, never by hand, so
 *     failing on one would demand the wrong edit.
 *   - OPT-OUT: a line carrying `uws-pin-allow: <reason>` is exempt, for a
 *     deliberately synthetic spec such as a unit-test fixture.
 *
 * The expected tag comes from the same derivation the runtime install hints use
 * (src/uws-load-hint.js), so the guard and the messages it protects can never
 * disagree about what the pin is.
 *
 * Dependency-free (no eslint), modeled on the sibling check-slugs /
 * check-determinism scripts, wired into `npm run check` and so into pretest.
 *
 * @module scripts/check-uws-pin
 */
import { readFileSync } from 'node:fs';
import { dirname, resolve, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { uwsInstallSpec } from '../src/uws-load-hint.js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// The git ref that follows the repo in an install spec. The ref class covers
// tags, branches and semver ranges; it stops at a quote, brace or whitespace so
// a template hole (`...js#${tag}`) yields no match rather than a bogus one.
const SPEC_RE = /uWebSockets\.js#([A-Za-z0-9._^~*+-]+)/g;

// Per-line opt-out, following the `determinism-allow:` idiom of the sibling
// guard. Reason text is for the reader; this script only looks for the marker.
const ALLOW_MARKER = 'uws-pin-allow:';

// Append-only history, plus this file (its own header spells the spec form out).
// Derived rather than hardcoded so renaming the guard cannot disarm it.
const SELF = relative(root, fileURLToPath(import.meta.url)).split('\\').join('/');
const SKIP_FILES = new Set(['CHANGELOG.md', SELF]);

// Generated by a package manager: reported, never enforced (see the header).
const LOCKFILES = new Set([
	'package-lock.json', 'npm-shrinkwrap.json', 'yarn.lock', 'pnpm-lock.yaml'
]);

/**
 * The pinned git ref, from the adapter's optionalDependencies.
 * @param {{ optionalDependencies?: Record<string, string> } | undefined} pkg
 * @returns {string | null} e.g. `v20.69.0`, or null when the spec carries no ref
 */
export function pinnedRef(pkg) {
	const spec = uwsInstallSpec(pkg);
	const hash = spec.indexOf('#');
	return hash === -1 ? null : spec.slice(hash + 1);
}

/**
 * Every install-spec reference in one file's text.
 * @param {string} text file contents
 * @param {string} pinned the pinned ref every reference must name
 * @returns {{ line: number, ref: string, stale: boolean, allowed: boolean }[]}
 */
export function scanText(text, pinned) {
	const refs = [];
	const lines = text.split(/\r?\n/);
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		SPEC_RE.lastIndex = 0;
		let m;
		while ((m = SPEC_RE.exec(line)) !== null) {
			refs.push({
				line: i + 1,
				ref: m[1],
				stale: m[1] !== pinned,
				allowed: line.includes(ALLOW_MARKER)
			});
		}
	}
	return refs;
}

/** Tracked files only: generated output and installed dependencies are hands-off. */
function trackedFiles() {
	// Tracked files PLUS untracked ones git would add, minus anything ignored. A
	// new file is untracked right up until the commit that ships it, so scanning
	// only the tracked set waves every new stale spec through on its way in - which
	// is exactly how a synthetic tag in a new test file first reached this guard
	// one commit too late.
	return execFileSync('git', ['ls-files', '-z', '--cached', '--others', '--exclude-standard'], {
		cwd: root,
		encoding: 'utf8'
	})
		.split('\0')
		.filter(Boolean);
}

function main() {
	const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
	const pinned = pinnedRef(pkg);

	console.log(`check-uws-pin: ${pkg.name}@${pkg.version}`);
	if (pinned === null) {
		console.error(`\ncheck-uws-pin FAILED: package.json optionalDependencies names no pinned`);
		console.error(`  uWebSockets.js ref. Pin it to a tag so every install site has one truth.`);
		process.exit(1);
	}
	console.log(`  pin: ${pinned} (package.json optionalDependencies).`);

	const files = trackedFiles().filter((rel) => !SKIP_FILES.has(rel));
	let total = 0;
	let allowed = 0;
	const stale = [];
	const lockfiles = [];

	for (const rel of files) {
		let text;
		try {
			text = readFileSync(join(root, rel), 'utf8');
		} catch {
			continue; // a tracked path missing from the working tree is not this guard's case
		}
		if (!text.includes('uWebSockets.js#')) continue;
		const isLockfile = LOCKFILES.has(rel.split('/').pop());
		for (const ref of scanText(text, pinned)) {
			total++;
			if (!ref.stale) continue;
			if (ref.allowed) { allowed++; continue; }
			(isLockfile ? lockfiles : stale).push({ rel, ...ref });
		}
	}

	console.log(
		`  ${files.length} tracked file(s) scanned, ${total} install-spec reference(s)` +
		`, ${stale.length} stale, ${allowed} opted out.`
	);

	// A lockfile out of step is real drift, but the fix is a reinstall, so it is
	// surfaced and left to a human rather than failing the build.
	for (const f of lockfiles) {
		console.log(`  note (generated lockfile behind the pin; rerun \`npm install\` there): ${f.rel}:${f.line} -> ${f.ref}`);
	}

	if (stale.length) {
		console.error(`\ncheck-uws-pin FAILED (${stale.length} stale install spec(s)):`);
		for (const f of stale) console.error(`  x ${f.rel}:${f.line}  names ${f.ref}, pin is ${pinned}`);
		console.error(`  Update each site to the pinned tag - or, in runtime code, derive it from`);
		console.error(`  optionalDependencies with uwsInstallSpec() from src/uws-load-hint.js. A`);
		console.error(`  deliberately synthetic spec opts out with "${ALLOW_MARKER} <reason>" on its line.`);
		process.exit(1);
	}

	console.log(`  OK - every install spec names the pinned ref.`);
}

// Importable for its own test suite; only the CLI invocation runs the check.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
